name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
    types: [checks_requested]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run test
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "Failing test on pull request"
            exit 1
          else
            echo "Test passed on merge queue!"
          fi 